name: Deploy to Railway

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  check:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    
    - name: Lint with flake8
      run: |
        # Stop build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # Exit-zero treats all errors as warnings
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    
    - name: Check for sensitive data
      run: |
        # Check if any API keys are hardcoded (should use env vars)
        if grep -r "AIzaSy" --include="*.py" .; then
          echo "Warning: Potential API keys found in code"
        fi
    
  notify:
    runs-on: ubuntu-latest
    needs: check
    if: success()
    
    steps:
    - name: Deployment notification
      run: |
        echo "✅ All checks passed! Railway will auto-deploy from main branch."
